### ISSUE TITLE
Only consume header by in decode_length_delimited if input buffer contains the entire message

### ISSUE THREAD

**Issue by YetAnotherMinion** [danburkert/prost#108]
Right now it is difficult to use `decode_length_delimited` with TCP streams because reading the length header advances the buffer before checking if the buffer is long enough to contain the message. This gives any input buffer only a single chance for decoding a message.

Proof of concept fix.
```diff
diff --git a/src/encoding.rs b/src/encoding.rs
index 78b4105..0d144af 100644
--- a/src/encoding.rs
+++ b/src/encoding.rs
@@ -52,6 +52,14 @@ pub fn encode_varint<B>(mut value: u64, buf: &mut B) where B: BufMut {
 
 /// Decodes a LEB128-encoded variable length integer from the buffer.
 pub fn decode_varint<B>(buf: &mut B) -> Result<u64, DecodeError> where B: Buf {
+    let (value, advance) = peek_decode_varint(buf)?;
+    buf.advance(advance);
+
+    Ok(value)
+}
+
+/// Decodes a LEB128-encoded variable length integer from the buffer without advancing the Buf.
+pub fn peek_decode_varint<B>(buf: &B) -> Result<(u64, usize), DecodeError> where B: Buf {
     // NLL hack.
     'slow: loop {
         // Another NLL hack.
@@ -72,10 +80,9 @@ pub fn decode_varint<B>(buf: &mut B) -> Result<u64, DecodeError> where B: Buf {
             }
         };
 
-        buf.advance(advance);
-        return Ok(value);
+        return Ok((value, advance));
     }
-    decode_varint_slow(buf)
+    peek_decode_varint_slow(buf)
 }
 
 /// Decodes a LEB128-encoded variable length integer from the slice, returning the value and the
@@ -120,16 +127,16 @@ fn decode_varint_slice(bytes: &[u8]) -> Result<(u64, usize), DecodeError> {
     Err(DecodeError::new("invalid varint"))
 }
 
-/// Decodes a LEB128-encoded variable length integer from the buffer, advancing the buffer as
-/// necessary.
+/// Decodes a LEB128-encoded variable length integer from the buffer.
 #[inline(never)]
-fn decode_varint_slow<B>(buf: &mut B) -> Result<u64, DecodeError> where B: Buf {
+fn peek_decode_varint_slow<B>(buf: &B) -> Result<(u64, usize), DecodeError> where B: Buf {
     let mut value = 0;
-    for count in 0..min(10, buf.remaining()) {
-        let byte = buf.get_u8();
+    let bytes = buf.bytes();
+    for count in 0..min(10, bytes.len()) {
+        let byte = bytes[count];
         value |= u64::from(byte & 0x7F) << (count * 7);
         if byte <= 0x7F {
-            return Ok(value);
+            return Ok((value, count + 1));
         }
     }
 
@@ -1011,7 +1018,7 @@ mod test {
             let roundtrip_value = decode_varint(&mut encoded.into_buf()).expect("decoding failed");
             assert_eq!(value, roundtrip_value);
 
-            let roundtrip_value = decode_varint_slow(&mut encoded.into_buf()).expect("slow decoding failed");
+            let roundtrip_value = peek_decode_varint_slow(&mut encoded.into_buf()).expect("slow decoding failed").0;
             assert_eq!(value, roundtrip_value);
         }
 
diff --git a/src/message.rs b/src/message.rs
index 5648a9d..b927064 100644
--- a/src/message.rs
+++ b/src/message.rs
@@ -66,6 +66,12 @@ pub trait Message: Debug + Send + Sync {
 
     /// Decodes a length-delimited instance of the message from the buffer.
     fn decode_length_delimited<B>(buf: B) -> Result<Self, DecodeError> where B: IntoBuf, Self: Default {
+        let buf = buf.into_buf();
+        let (len, varint_len) = peek_decode_varint(&buf)?;
+        let remaining = buf.remaining();
+        if len > (remaining - varint_len) as u64 {
+            return Err(DecodeError::new("buffer underflow"))
+        }
         let mut message = Self::default();
         message.merge_length_delimited(buf)?;
         Ok(message)
@@ -84,8 +90,8 @@ pub trait Message: Debug + Send + Sync {
 
     /// Decodes a length-delimited instance of the message from buffer, and
     /// merges it into `self`.
-    fn merge_length_delimited<B>(&mut self, buf: B) -> Result<(), DecodeError> where B: IntoBuf, Self: Sized {
-        message::merge(WireType::LengthDelimited, self, &mut buf.into_buf())
+    fn merge_length_delimited<B>(&mut self, mut buf: B) -> Result<(), DecodeError> where B: Buf, Self: Sized {
+        message::merge(WireType::LengthDelimited, self, &mut buf)
     }
 
     /// Clears the message, resetting all fields to their default.
```

**Comment by danburkert** [comment]
I agree it would be useful to be able to do this sort of 'peek' operation in many cases, but unfortunately I believe this implementation (and any alternate implementation that I can think of) is not correctly using the `Buf` interface.  In particular the [docs][1] for `Buf.bytes()` read:

> Returns a slice starting at the current position and of length between 0 and Buf::remaining().

So it's perfectly valid for a `Buf` implementation with 10 available bytes to only return a subset, or even just a single byte.  I believe the interface is defined that way so that it can support structures where the bytes are not laid out contiguously, e.g. a rope.  As such, advancing the internal buffer's read pointer is necessary.  Incidentally, this is exactly why `decode_varint_slow` is necessary: it handles this case where the buf impl doesn't return a contiguous slice.

That being said, `IntoBuf` is very flexible, and for most `IntoBuf` implementations I'm aware of you can get peak-like functionality by shallow cloning the buf.  For example, let's say your buffer is an instance of `Bytes`: simply clone the instance before passing it into `decode_varint` and the original won't be modified (`Bytes::clone` should be very cheap).  If you're using a cursor, then you can usually just construct a new cursor pointing to the current section of the backing bytes.

As for the motivation behind this proposal, it's perfectly valid and I've felt the pain myself.  I'm going to move the discussion on that over to #106, though.

[1]: https://docs.rs/bytes/0.4.8/bytes/trait.Buf.html#tymethod.bytes

**Comment by YetAnotherMinion** [comment]
You are correct about API restrictions of `Buf`. My patch only worked because I was testing with `Bytes` and `BytesMut` which are continuous.

Related to the design of this library, the API of **bytes** is changing in 0.5 to remove the creation of a std::io::Cursor. `BytesMut` and `Bytes`  impl `Buf` directly, and calling `.into_buf()` will consequently return the original object unchanged.

Currently, passing a `Bytes` or `BytesMut` to decode does not modify (calling advance) the buffer because the buffer is wrapped in an std::io::Cursor by the `.into_buf()` inside this library. It looks like there will ownership or mutability changes required in `src/message.rs` to use the upcoming version of bytes. I'll see what that looks like and submit a patch so prost can have support for new version of bytes on same day bytes 0.5 is released.
