### ISSUE TITLE
rustdoc does not emit Message impl for generated types

### ISSUE THREAD

**Issue by sharazam** [danburkert/prost#11]
I am not sure if I am too dumb, but I couldn't figure out how to actually read a file using the generated code  an example would be really helpful.

Using prost, I've generated the rust bindings for the OpenStreetMap .pbf files: https://crates.io/crates/osm-proto-rs

And here is a small PBF file, for testing: https://github.com/sharazam/small-test-pbf-file

How do I read the file, for example the header block? Do I use bytes or just `File::open` or is there a hidden "Reader" somewhere? Thanks in advance.

**Comment by danburkert** [comment]
Hi @sharazam I left a comment on reddit here: https://www.reddit.com/r/rust/comments/6jyhmx/prost_a_protocol_buffers_implementation_for_the/djikvj9/, but I'll expand a bit on your options for decoding from a file.  The simplest way is, as I mentioned, to read the entire file into a `Vec<u8>` using something like [`Read::read_to_end`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.read_to_end).  If the file is really big and you want to do it more lazily, you could also read-as-you-go, since the OSM format appears to be length-prefixed.  Read the length-prefix, then read that much into the buffer.  Another option is to use the `memmap` crate to map the file to a slice, which can then be wrapped in a `Cursor` to get a `Buf` impl.

**Comment by sharazam** [comment]
Yes, I know how to read a file. What I don't get is how I should serialize the file into the structs. That's what protobuf is for, isn't it? I've published version 0.2 of the osm-pbf-rs library with the fileformat.proto file added: https://docs.rs/osm-proto-rs/0.2.0/osm_proto_rs/

But there is no "decode" method like you mentioned, nothing. How should I serialize the PBF file into structs, I thought that was what protobuf was for?

**Comment by danburkert** [comment]
Interesting, I think there may be a bug in rustdoc.  The encode method comes from an impl of the [`Message`](https://docs.rs/prost/0.1.0/prost/trait.Message.html) trait.  Every Rust struct generated by `prost` has a derived impl of `Message`.  I do see the issue where the rustdocs aren't listing that, though, and I'll look into that.

**Comment by danburkert** [comment]
This was indeed due to a rustdoc bug.  See the commit message in 0bdd87889ff7e56bc051d811fc0020c225569f2c for the gory details.  Thanks again for the report!
