### ISSUE TITLE
Documentation for 0.4.0 prost-build missing

### ISSUE THREAD

**Issue by marcelbuesing** [danburkert/prost#125]
While the documentation works fine for [0.3.2](https://docs.rs/prost-build/0.3.2) it's broken for [0.4.0](https://docs.rs/prost-build/0.4.0/prost_build/). Currently I see a `The requested resource does not exist`.

**Comment by ebkalderon** [comment]
According to the [build logs](https://docs.rs/crate/prost-build/0.4.0/builds/105277), the main issue is that the `PROTOC` and `PROTOC_INCLUDE` environment variables are missing. There exists a workaround committed on June 21 that fixes this ([`5f54a1b`](https://github.com/danburkert/prost/commit/5f54a1be5e4a3c85734f14c3ec23a09bd9cfa609)), but it doesn't appear to have been released yet. It would be nice to have this commit pushed up as a new patch release so users can access documentation from the official sources.

CC @danburkert

**Comment by danburkert** [comment]
Sorry for slow response on this.  Yes, 5f54a1be5e4a3c85734f14c3ec23a09bd9cfa609 introduced a fix for this issue.  In separate news, it was just announced that the longstanding issues with docs.rs were [fixed](https://www.reddit.com/r/rust/comments/9q41wv/docsrs_is_now_part_of_the_rustlangnursery/), and it does appear that 0.4.0 docs have been built.  I'm going to leave this issue open, since I'm considering reverting 5f54, since it's something of a hack and introduced an otherwise useless cargo feature.  Rarely does procrastination ever work out so well...

**Comment by danburkert** [comment]
Woops, I checked `prost` and not `prost-build`.  Seems I'm still on the hook for a minor release, and the commit can't be reverted.

**Comment by danburkert** [comment]
Actually it may still be in the process of rebuilding or stuck in a queue.  https://docs.rs/crate/prost-build/0.4.0/builds doesn't show any rebuilds since June.  I'm going to give it some time.  If that doesn't work I'll ping the docs.rs people to see if kicking it manually will update the docs.

**Comment by nrc** [comment]
Confirming docs are now fine: https://docs.rs/crate/prost-build/0.4.0

**Comment by marcelbuesing** [comment]
Thanks =) !
