### ISSUE TITLE
Prost should not require user to include a `bytes` dependency.

### ISSUE THREAD

**Issue by carllerche** [danburkert/prost#127]
By doing [`extern crate bytes`](https://github.com/danburkert/prost/blob/e6aaddc259409db2193b4eae6ac064fdea319fb6/prost-derive/src/lib.rs#L178) in the generated derive, Prost requires the user to add a bytes dependency.

Instead, the prost crate should re-export bytes. I have done this in the past by having a hidden `codegen` module w/ the re-exports. [Example](https://github.com/carllerche/tower-web/blob/master/src/codegen/mod.rs).

**Comment by carllerche** [comment]
If this sounds good to you, I can work on a PR.

**Comment by LucioFranco** [comment]
This could be done via moving proc macros to a internal crate then using a facade crate to export bytes, prost and prost-types at the top level. This would allow us to drop bytes deps.

cc @danburkert I'm happy to work on this.

**Comment by danburkert** [comment]
I dropped the `extern` statements in a recent commit (https://github.com/danburkert/prost/commit/1efcabfe7b193084bd1d913ffa5698a7a96386a2#diff-7b8f088fd81bbb3a795cd5390c9ebcb2L438-L439).  Crates that depend on `prost`/`prost-derive` still need to depend on `bytes` as well, but I don't see that as problematic, it's very much part of the public API.  Is there another reason to prefer re-exporting?

**Comment by LucioFranco** [comment]
@danburkert mostly, we've seen it as a big issue for new users getting used to `tonic` https://github.com/hyperium/tonic/issues/123. Within tonic myself I like to have a codegen module that contains what `tonic-build` uses. I think overall it just provides a bit of a smoother onboarding path and reduces the chances that someone brings in the wrong version. The other reason is that if you do miss the import you get some decently cryptic error messages.

**Comment by danburkert** [comment]
This seems like a documentation issue to me; re-exporting the API does mean the user doesn't need to know about `bytes` during initial setup, but it's not like the user can remain isolated long, since `Buf`/`BufMut` are fundamental parts of the `prost` API.  The user's going to need to use these traits, and I don't think they should be referenced through a `prost` namespace.

**Comment by LucioFranco** [comment]
I agree its probably a documentation issue, and I've tried to see if multiple methods work. The one caveat to your point there is that to use `tonic` you don't actually need to know about buf/bufmut or bytes at all since that is encapsulated via the `tonic` implementation. So in reality in a basic tonic application, you import bytes but never use it directly.

I totally understand the viewpoint from users that might use only prost. Happy to go either way, or if you have suggestions on how to make sure users import bytes.

Since, prost relies on bytes anyways, would it make sense to reexport it? Not sure what we would lose if we reexported bytes or used a facade crate for derive. 

Anyways, happy to work around what ever :)

**Comment by danburkert** [comment]
I'd prefer not to reexport `bytes` since it's otherwise exposed to users of `prost`, and I think having two ways to get at the types would create more confusion in the long term.  For instance, my understanding is that the docs for generated types would point to the re-exported interface and not the `bytes` crate on docs.rs.  If there were a way to do it without exposing the re-exported interface to downstream crates I'd be OK with that, but AFAIK that's not possible.

**Comment by carllerche** [comment]
I understand your hesitation, but i don't think that "having two ways to get at a type" is the right way to think about it. If you re-export the types, they would be `doc(hidden)` in some `prost::__codegen_helper_dont_use_this` module and generated code could include a comment on top of the use statements indicating that users should depend directly on bytes if they wish to use the types.

I believe re-exporting types is considered the idiomatic solution to the problem.

**Comment by danburkert** [comment]
@carllerche I see, do you have any examples of this?  I want to see what the generated docs look like.

**Comment by LucioFranco** [comment]
Is one that I can think of off the top of my head https://docs.rs/tokio-rustls/0.12.1/tokio_rustls/

**Comment by danburkert** [comment]
OK I think I see.  I'm open to a PR introducing this as long as generated docs do not link to the re-export (in both `prost` and crates with generated types, e.g. `prost-types`).

Note that I think this won't be possible with `prost-types` since `prost-types` depends on `prost`, so I don't think it can be re-exported?

**Comment by danburkert** [comment]
Also isn't this an issue for `prost` itself from the perspective of `tonic` users?  I don't really see the win...

**Comment by LucioFranco** [comment]
@danburkert the issue from tonic's end is that if users enable the prost encoding they need to include `prost`, `prost-types` and `bytes`. Which is a bit of a pain and easy to forget to include one.

I'll open a PR soon.

**Comment by carllerche** [comment]
I don't think the re-exports should show up at all in docs.

In `tower-web`, I add [`#[doc(hidden)]`](https://github.com/carllerche/tower-web/blob/master/src/codegen.rs#L1) and there is no mention of the exports in docs: https://docs.rs/tower-web/0.3.7/tower_web/

**Comment by LucioFranco** [comment]
I think in this case because the `Message` trait contains `Buf` trait bounds it makes sense to expose it, since the user is forced to use it.

**Comment by danburkert** [comment]
Should be fixed as of 0.6.0.  Thanks @LucioFranco and @carllerche .
