### ISSUE TITLE
Enumerations and CamelCase

### ISSUE THREAD

**Issue by pimeys** [danburkert/prost#14]
I happened to notice a behavior with prost code generator, that doesn't convert enum items correctly. It seems to make the assumption the items are `snake_case`, converting them to `CamelCase`. In our case, the enum values are already in `CamelCase`, but then they are converted into broken `Camelcase`, which is hard to read and now when converting our projects from rust-protobuf to prost, breaks lots of things.

What is the expected behavior? Always having proto enums in `snake_case` and then in Rust `CamelCase`? Allowing `CamelCase` in proto and converting it to `Camelcase` in Rust or detecting if proto has already `CamelCase` and converting it correctly to `CamelCase` in Rust?

**Comment by pimeys** [comment]
Basically this works in our case, and didn't seem to break any tests:

https://github.com/pimeys/prost/commit/9d2233e70e7c70184734790e1d2cc667ab5e805c

**Comment by danburkert** [comment]
Thanks for the report, @pimeys!  The [Protobuf style guide](https://developers.google.com/protocol-buffers/docs/style) does recommend using shouty snake case, but clearly `prost` shouldn't fail like this with Rust-styled variants. I think the way I want to handle this is by improving the ident conversion code, instead of doing recognition via regex.  Towards that end, I posted #15.  Would you mind testing out that PR and making sure it fixes your issue?

**Comment by pimeys** [comment]
I'm all in with not using regex. It was just a quick test to see how far I can get my refactoring to not use rust-protobuf in one of our projects.

I'll give this a spin tomorrow when I get to the office.

**Comment by danburkert** [comment]
This is fixed by c1902708e99e1ba0a1aae00401e32d7f6902869e.
