### ISSUE TITLE
Question: Why are repeated field relations not added to the message graph?

### ISSUE THREAD

**Issue by timthelion** [danburkert/prost#148]
I see that when building the message graph in the compiler code, repeated fields are ignored. Why?

https://github.com/danburkert/prost/blob/master/prost-build/src/message_graph.rs#L52

**Comment by danburkert** [comment]
That’s because the sole use of the message graph is detecting recursively
nested messages and co-recursively nested messages.   Because prost does
not box message fields, recursively nested messages would not compile in
Rust. To allow it, the message graph is used to detect the situation and
automatically box the recursive field.   Since repeated messages are
already put in a Vec, the extra indirection isn’t necessary.
