### ISSUE TITLE
prost_build: Add a not matching path mechanism

### ISSUE THREAD

**Issue by Sushisource** [danburkert/prost#150]
Hi there, really like Prost, great library.

One thing I've just run in to that's a bit rough is I have
```rust 
    config.type_attribute(".", "#[derive(new)]");
```

In my prost build config right now, which was all hunky-dory until I added an enum, which doesn't work with new. It would be really great if there was some mechanism to tell a `type_attribute` when to *not* match. For example, a third parameter / overload with a list of paths that the attribute should *not* apply to.

I don't have much extra time right now, but if I get some I'm happy to contribute a PR if this is something you want to add

Thanks!

**Comment by danburkert** [comment]
@Sushisource not related to to the feature request, but I'd caution against using derive-new with prost generated types.  Every prost type already implements `Default`, so it's not necessary, and derive-new won't respect the default values defined in your .protos.

As for the feature request, I'm not really that keen on extending the matching capabilities, since it seems like a very deep rabbit hole (do we support regex?  etc.).  However, it would be really nice if you could specify that a derive attribute should cascade to all types which a message contains.  This is harder to implement, but much more intuitive IMO.  The basics of the implementation are already in prost since we create an object graph for tracking recursively nested types.

**Comment by danburkert** [comment]
> @Sushisource not related to to the feature request, but I'd caution against using derive-new with prost generated types. Every prost type already implements `Default`, so it's not necessary, and derive-new won't respect the default values defined in your .protos.

Woops, nevermind I didn't realize what derive-new was providing.  Seems fine, if a little redundant with explicit field initialization.

**Comment by Sushisource** [comment]
@danburkert I get your concern about it getting real complicated. I think the approach you outlined makes sense. That said, I'd still argue that a simple "apply the attribute to everything that matches this path, except the ones that match these paths" is fairly intuitive and not complex to implement.

That said, the "no cascade" option would've worked fine for me in this instance.

I had to result to a super dirty hack in my build.rs that removes them with sed. I felt pretty unclean after that, so seems at least *some* kind of solution is in order.

**Comment by danburkert** [comment]
Revisiting this - I think the answer is to just provide an empty overriding `type_attribute` for just the enum type:

```
// Add derive new for all types by default.
config.type_attribute(".", "#[derive(new)]");
// But for this specific type, don't derive new.
config.type_attribute(".", "");
```

Feel free to re-open if that doesn't work for you.

**Comment by gorzell** [comment]
I also have a case where I want to add a `#[serde(default)]`, but it can only be added to the structs, and not the enums.

@danburkert I can't re-open this, but I did try your work around, and it doesn't quite seem to work.  The `type_attributes` appear to be additive, which isn't all that surprising, but means you just end up with a new line, rather than a replacement.

```rust
#[derive(serde::Serialize,serde::Deserialize)]
#[serde(default)]

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Foo {
```

I can list every message by hand, but that does mean this has to be kept up to date when new messages are added, which is a bit of a shame.
