### ISSUE TITLE
Consider adding `#![allow(dead_code)]` in generated files

### ISSUE THREAD

**Issue by overvenus** [danburkert/prost#19]
Hello,

If there was any message or field in generated files we don't use, rustc blames.

```
warning: method is never used: `b1`
  --> perftest_data_prost.rs:43:35
   |
43 | #[derive(Clone, Debug, PartialEq, Message)]
   |                                   ^^^^^^^
   |
   = note: #[warn(dead_code)] on by default
```

```
#[derive(Clone, Debug, PartialEq, Message)]       // <== line 43.
pub struct TestBytes {
    #[prost(bytes, optional, tag="1")]
    pub b1: Option<Vec<u8>>,
}
```

Since they are generated, adding `#![allow(dead_code)]` seems reasonable to me. What's you option?

**Comment by danburkert** [comment]
Yep, looks reasonable, and the fix is straightforward, I'll post a patch shortly.  Thanks for putting together the benchmarks!  Left you some small fixes in overvenus/quick-protobuf/pull/1 since I wanted to check it out, and I've broken the API recently.  I think I'm just about ready to release a 0.2; the Message trait shouldn't be seeing any more breaking changes for the foreseeable future.  Looks like `prost` is competitive in those benchmarks in write performance, but has some improvements to make on the read side.  I suspect #4 is the culprit.  I'm probably going to see what I can do about that, but if you have any ideas or want to contribute in the area It'd be appreciated.
