### ISSUE TITLE
Allow specifying the output filename

### ISSUE THREAD

**Issue by rlabrecque** [danburkert/prost#226]
Hi there, I'm using prost via tower-grpc, and one thing that I'd love to do is override the output filename like I can do with out_dir.

https://github.com/danburkert/prost/blob/master/prost-build/src/lib.rs#L545

This would allow me to do something like:
```

fn main() {
    std::env::set_var("OUT_DIR", "src/health/");
    let mut config = prost_build::Config::new();
    config.out_dir("src/health/");
    config.out_filename("mod.rs");
    config.compile_protos(&["proto/health.proto"],
                                &["proto/"]).unwrap();
}
```

Then I could use the proto like:

`use health;` instead of `include!(concat!("./grpc.health.v1.rs"));`

I've worked around this currently by outputting into that folder, with a mod.rs just containing the `include!()`

**Comment by rlabrecque** [comment]
I've learned that setting the OUT_DIR to "src/*" causes unnecessary recompiles to happen all the time, so this probably isn't worth caring about. Feel free to close it!

**Comment by danburkert** [comment]
It's not possible to provide an API which would allow you to override the
output file name, since there may be multiple output files per proto
compilation.  The 'correct' way to do this is to change the package
declaration in your source .proto files.  Also note that prost discourages
checking in generated code, which is why this workflow isn't well supported.

- Dan
