### ISSUE TITLE
prost-build forces prost 0.5.0 which does not include r#Self bugfix.

### ISSUE THREAD

**Issue by jpittis** [danburkert/prost#259]
Here's the discussion from the tonic project: https://github.com/hyperium/tonic/issues/225

`prost-build` version 0.5.0 specifies `prost` 0.5.0 ([Cargo.toml](https://github.com/danburkert/prost/blob/master/prost-build/Cargo.toml#L20)) which does not include the bugfix found in https://github.com/danburkert/prost/commit/f51cbb2d23fe1c044309f8ab14473b0db61c3ffe on the master branch.

I was hoping to write some kind to take advantage of that fix. Any suggestions on how to proceed?

**Comment by danburkert** [comment]
The issue here is that a fix isn't yet released, not that prost-build's dependency version is incorrect (FYI `0.5.0` does not pin to exactly `0.5.0` https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio).  A new version of `prost` is actively being worked on, and will be released soon.

**Comment by jpittis** [comment]
Pardon the silly question but if I point my Cargo.toml to use `master`, I would get this fix right?

**Comment by danburkert** [comment]
Yes, that's correct.  It gets a bit hairy with tonic, though.  There's some discussion about this in the `prost` room of the tokio discord from yesterday.

**Comment by jpittis** [comment]
Alrighty. Gonna close this. Thanks so much for the fast response and all your work with prost. <3
