### ISSUE TITLE
Can't detect partial protobuf message with decode_length_delimited

### ISSUE THREAD

**Issue by megmacattack** [danburkert/prost#32]
In a non-blocking context I need to detect if I don't have enough bytes to consume an entire protobuf message so I can wait for more bytes and try again. Right now, `decode_length_delimited`'s interface looks like it can only tell me if parsing succeeded or failed, with failure reasons in a fairly opaque error object.

I don't really have a good suggestion for how to represent this in the function interface, unfortunately. Especially if you want to stick to Result types.

**Comment by danburkert** [comment]
The trick here is to try to decode the length delimiter up front, then only continue if you have enough bytes.  This is a bit trickier than it should be with a variable length delimiter, since you don't necessarily know up front if you even have enough bytes to decode the delimiter.  If possible, I'd recommend using a fixed-length delimiter (`byteorder` makes this easy).  If you have to use a variable length delimiter, `prost` does include a way to decode a varint, but (fair warning) it's undocumented and may change in patch releases.  Check out [`prost::encoding::decode_varint`](https://github.com/danburkert/prost/blob/master/src/encoding.rs#L54).  If `decode_varint` fails, either the input is malformed, or you don't have enough input, however you can rely on varints being a maximum of 10 bytes.

**Comment by danburkert** [comment]
This may help, it's a fragment of an inner loop that's decoding `prost` messages from a tokio TCP connection:

```

**Comment by danburkert** [comment]
Going to close this out, but feel free to re-open if you're still having an issue with `prost`.
