### ISSUE TITLE
Using borrowed values

### ISSUE THREAD

**Issue by walfie** [danburkert/prost#35]
Currently everything is using `String` and `Vec<u8>` -- are there any plans in the future to allow supporting borrowed types like `Cow<'a, str>` and `Cow<'a, [u8]>`? Maybe it could be toggleable via some flag in build.rs.

A lot of times I'm creating an instance of a Prost-generated struct just to convert it to bytes immediately after, or I'll have a bunch of Prost structs that point to the same data (e.g., a `&'static str` error message), so in those cases I don't need the struct to own the data.

**Comment by danburkert** [comment]
There are no such plans.  Adding lifetime parameters to `Message` structs would cause the implementation to be significantly more complex.  You may be interested in #31, the issues are similar, but the solution proposed there would be much easier to integrate.  Also, you may want to check out https://github.com/tafia/quick-protobuf.

**Comment by vorner** [comment]
Hello

I'd also be a bit interested in this (though I'd prefer using `&str` and `&[u8]` over `Cow`, due to the interface). I understand you don't want to write it, as it would be a lot of work, but if I decided to do it, would you be considering to accept it, or would you consider it a burden to maintain it later on? (I guess it depends a bit on how much more complex it would be, I haven't done any research yet)

My battle plan would be something like:
* Make sure the parsers/serializers can work with lifetime constrained messages and `&str` and `&[u8]` (or maybe include `Cow` as well).
* Add option to the prost-build to be able to output either of these (owned, borrowed, cow). The user would still be able to get nice, owned messages.
