### ISSUE TITLE
Consider "inlining" oneof messages

### ISSUE THREAD

**Issue by Jragonmiris** [danburkert/prost#42]
In addition to #41, I was wondering if inlining message fields into oneof generated enums might be something you'd consider.

```
message Foo {
    oneof foo_type {
        Bar bar = 1;
        Baz baz = 2;  
        float y = 3;
    }
}

Bar {
    required string a = 1;
}

Baz {
    oneof baz_type {
        int32 id = 1;
        float number = 2;
    }
}
```

Can be interpreted as

```
// Omitting probably necessary module scoping

enum BazType {
    Id(int),
    Number(float),
}

enum FooType {
    Bar { a: String },
    Baz { baz_type: Option<BazType> },
    Y(f32),
}

struct Foo {
    foo_type: Option<FooType>   
}
```

Which also reduces stutter a lot. This would allow the code I mentioned in my reply to #41 to be (in addition to the switching to `Unknown` fields)

```
match self.specific_msg {
    SpecificMsg::Config { 
        which_module: WhichModule::CoreCfg {
            plugin_type: plugin_type,
        }
    } =>{ /* do things */ },
     SpecificMsg::Config { 
       which_module: WhichModule::CoreCfg {
            plugin_type:  OneOfEnum::Unknown,
        }
    } => panic!("Invalid plugin_type"),
    SpecificMsg::Config { 
        which_module: WhichModule::Unknown
     } => panic!("This module doesn't handle this type of config"),
    SpecificMsg::Unknown => panic!("Invalid variant denoting the specific message type"),
}
```

It's not quite as notable with this example, but it reduces the fact that all `oneof` fields have to be double nested which causes a lot of extra levels. It also looks a lot more like the Rust code I'd write to describe these types. Personally, I'd prefer having both an inline enum and a struct I can convert to (if the message occurs outside this context) that always having to use a struct. Because I have a lot of `oneof`s with marker messages like

```
message Foo {
    oneof type {
        A a = 1;
        B b = 2;
        C c = 3;
        D d = 4;
    }
}

message A {}
message B {}
message C {}
message D { required string name = 1; }
```

Because marker messages reduce error handing from the other way of doing this (enums with accompanying optional fields) as well as improving future extensibility.

To me this is basically the exact same thing as writing

```
enum Foo {
    A,
    B,
    C,
    D { name: String },
}
```

(Albeit prost would probably generate a struct with one field for Foo which is fine, I don't expect too complex of auto-sugaring).

This is neglecting the `Option`/`Unknown` variant of course, but if #41 is not adopted in favor of `Unknown` variants, there's no harm in just generating `struct Foo { type: Option<foo::Type> }` and if it is it's just an extra variant.

I'll admit there are some questions about the semantics here with regards to if you can/should do this if a message is used both as a field and in a oneof, but personally I'd prefer having both a standalone and an inlined variant available to having to use the struct because I tend to use deeply-nested messages. At the very least, I think this should be done if it appears a message is only used as a oneof variant.

**Comment by danburkert** [comment]
I've been thinking about this.  Unfortunately it would be very hard to support two different representations of `oneof`s, and it would add a lot of testing surface area.  I'm inclined to stick with wrapping `oneof`s in an `Option` for one important reason: once the `Option` part of the field has been peeled away, the inner `oneof` type can be operated on without worrying about non-existence, including passing it to another method.

Unfortunately there is an impedance mismatch between Protobufs and Rust.  The over-abundance of `Option`al fields is also an issue when working with `proto2`, which I do a lot.  I've found defining a helper trait like the following in the end-user project to be really helpful for dealing with protobuf-optional fields which are in reality required in order to make sense of a message:

```rust
pub trait ExpectField {
    type Value;
    fn expect_field(self, message: &'static str, field: &'static str) -> Result<Self::Value, Error>;
}

impl <T> ExpectField for Option<T> {
    type Value = T;
    fn expect_field(self, message: &'static str, field: &'static str) -> Result<T, Error> {
        match self {
            Some(value) => Ok(value),
            None => Err(Error::Serialization(format!("required field absent: {}::{}",
                                                     message, field))),
        }
    }
}
```

(obviously this will need to be adapted to whatever error type you are using in your application).  

The idea is that when you are unpacking the message with optional fields, you can call `expect_field("MessageName", "field_name")?`, which is a pretty light-weight way to handle the non-existence.  If you are OK panicking, `expect_field` could return `T` instead of a result.
