### ISSUE TITLE
Examples & Suggested Error Handling for Encode/Decode

### ISSUE THREAD

**Issue by ameets** [danburkert/prost#48]
Are there any examples on how to properly use encode and decode?

I've been using the following structure but am not sure if it's best to cast the expected proto type on decode. Would also appreciate any suggestions on recommended error handling.

```
let request = protos::my::custom::proto{};
let mut request_buffer = BytesMut::with_capacity(4096);

request.encode(&mut request_buffer).expect("encode error");

let result : Result<protos::my::custom::proto, DecodeError> = Message::decode(request_buffer) ;
assert_eq!(result.unwrap(), request);
```

Thanks!

**Comment by danburkert** [comment]
Hi @ameets, I think your best bet at this point is taking a look at some of the tests in the repository.  For instance, here's a test that decodes a message, and then encodes it: https://github.com/danburkert/prost/blob/master/tests/src/lib.rs#L83.

As far as error handling, encoding can only fail due to insufficient buffer space.  Decoding can fail if the data is malformed.

**Comment by ameets** [comment]
Thanks!

**Comment by Stvchm9703** [comment]
Although this thread was closed, I still feel confuse about the encoding/decoding after looking the doc and the  test-case,
for example: how I encode/decode the data struct after auto-gen the struct from proto file ?
