### ISSUE TITLE
Nicer `Debug` for enums

### ISSUE THREAD

**Issue by vorner** [danburkert/prost#49]
Hello

I understand why enums are encoded as numbers in the resulting structure. Still, having the `Debug` trait output the number is a bit uncomfortable, eg:

```
Message { stuff: Some(3) }
```

Would it be possible to provide a custom `Debug` implementation that would provide the enum variant instead of the number if there's one available and fall back to the number if the name is unknown?

**Comment by danburkert** [comment]
This is a great idea.  I'm not going to have time to work on it immediately, but let's keep this issue open to track.

**Comment by vorner** [comment]
I started playing around with it. It turns out a bit harder than I expected (without any insult, the code in the code generator is a bit spaghetti style ‒ and my experiments aren't helping either). Maybe I'm going about it in a wrong way (I'm trying to add it into the `prost-build` crate). And it has another disadvantage ‒ it pollutes the generated code and it is no longer as nice.

I was wondering about an alternative. Instead of having an `i32` field and a companion enum, what about having a real enum and adding an `Unknown(i32)` variant to it (with some fallback strategy on collision)? That would be a breaking change, but on the other hand, the resulting code would be more rusty ‒ it would prevent confusing one enum with other and it would be more convenient to use.

Or at least adding a newtype `EnumerationValue(i32)` for each enumeration?

**Comment by danburkert** [comment]
> I started playing around with it. It turns out a bit harder than I expected (without any insult, the code in the code generator is a bit spaghetti style ‒ and my experiments aren't helping either). Maybe I'm going about it in a wrong way (I'm trying to add it into the prost-build crate). And it has another disadvantage ‒ it pollutes the generated code and it is no longer as nice.

Yeah, I think the way this should be done is to generate the `Debug` impl during the derive step.  This is, for example, how the custom `Default` impl for enums works: https://github.com/danburkert/prost/blob/master/prost-derive/src/lib.rs?utf8=%E2%9C%93#L248-L252.

> I was wondering about an alternative. Instead of having an i32 field and a companion enum, what about having a real enum and adding an Unknown(i32) variant to it (with some fallback strategy on collision)? That would be a breaking change, but on the other hand, the resulting code would be more rusty ‒ it would prevent confusing one enum with other and it would be more convenient to use.

I considered this, but in the end I think it's better to do the current style, and have getter/setter methods that work with the enum type.  For example, here's a [message type|https://docs.rs/prost-types/0.2.3/prost_types/struct.FieldDescriptorProto.html] which includes a few enum fields, notice how they have getters/setters like `fn label(&self) -> Label`  and `fn set_label(&mut self, value: Label)` which work directly on the more ergonomic enum types instead of `i32`.

**Comment by vorner** [comment]
I already started another experiment in the derive part. It seems a better match, but I still have to hijack the `Debug` of the whole message.

I must admit I haven't known about the getters/setters (maybe I haven't read the documentation thoroughly enough, or maybe the generated methods are just well hidden). It actually makes it much better to use than I've expected. I still do wonder if there's a better solution for the problem ‒ another that crossed my mind is `Result<TheEnum, i32>`.

**Comment by vorner** [comment]
I think this can be closed now.
