### ISSUE TITLE
Auto-detection of local protoc

### ISSUE THREAD

**Issue by vorner** [danburkert/prost#57]
Hello

I've noticed the prost-build can be told to use local `protoc` command instead of downloading and building one itself. This is great thing for various offline build environments.

However, would it be possible to detect if protoc is available automatically and greatly speeding up compilation out of the box?

**Comment by danburkert** [comment]
I'm hesitant to do this because there's no telling where the protoc in the path came from, what version it is, etc.  The current method is pretty heavy weight, but at least it results in reproducible builds when moving from one environment to another (I'm not very keen on trying to debug peoples weird environment issues).  I'm happy to hear more pro/con arguments, though, if the current way is causing issues.

**Comment by danburkert** [comment]
Oh I forgot the main issue - I'm not aware of a good way to find the protoc include directory, which is often necessary.

**Comment by vorner** [comment]
I was thinking about checking `protoc --version` and whitelisting known versions.

I don't know what the include directory is for, but I guess that one might be a problem :-|.

**Comment by danburkert** [comment]
The protoc include directory is necessary if the .protos you compile reference any built-in protobuf types, e.g. the types exposed by `prost-types`.

**Comment by vorner** [comment]
I see. So I guess this can be closed until someone comes up with idea how to get that directory.
