### ISSUE TITLE
Nested, imported identifier causes "too many initial supers" error

### ISSUE THREAD

**Issue by caipre** [danburkert/prost#74]
I'm importing [`google.rpc.status`](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) in my proto and then embedding that type [within a `oneof`](https://github.com/caipre/chord/blob/master/rpc/v1/chord.proto#L87). When building, I see this error:

```
error[E0433]: failed to resolve. There are too many initial `super`s.  --> /path/to/target/debug/build/chord-687b2102b1406e1a/out/chord.v1.rs:97:29
   |
97 |         Error(super::super::super::google::rpc::Status),
   |                             ^^^^^ There are too many initial `super`s.

error: Compilation failed, aborting rustdoc
```

I think these `super`s are generated by [`resolve_ident`](https://github.com/danburkert/prost/blob/06946f78d6b26a7616c3c1c2b42afc997e2dbf8e/prost-build/src/code_generator.rs#L620-L623). Perhaps the `ident_path` has an extra term since it's part of a `oneof`? I'll try to take a closer look tomorrow.

**Comment by caipre** [comment]
FWIW, manually editing the generated code to remove one level of `super` resolves the problem. Note that you also have to import the `google.rpc.rs` file, since it's a nonstandard type; see https://github.com/danburkert/prost/issues/34 and https://github.com/caipre/chord/blob/prost/src/lib.rs#L6-L10 .

**Comment by danburkert** [comment]
@caipre I _think_ the issue may be a mismatch between the package in your chord.proto and the modules in your rust code, in particular these lines:

https://github.com/caipre/chord/blob/prost/rpc/v1/chord.proto#L3
https://github.com/caipre/chord/blob/prost/src/lib.rs#L12-L14

Notice that the protobuf package is `chord.v1`, while the rust module is `chordv1`.  Try out changing the Rust code to

```rust
pub mod chord
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/chord.v1.rs"));
    }
}
```

I couldn't actually test this since it appears building requires some kind of google .proto thing to be installed in `/usr/local/include` or `/usr/include` which I don't have.

**Comment by caipre** [comment]
@danburkert d'oh, of course you're right! I actually was doing that for the `google::rpc` module, but apparently didn't notice for my own `chord::v1` module. I blame working at midnight. 😄
