### ISSUE TITLE
Suggestion for enumerations

### ISSUE THREAD

**Issue by vorner** [danburkert/prost#76]
Hello

I'm still a bit unhappy about the fact enumerations are i32 values, for two reasons:

* Handling them is cumbersome. I can't just access the field, I have to convert it first…
* They are interchangeable. Let's say I have enums `enum Direction { Unspecified = 0, In = 1, Out = 2 }` and `enum Proto { Unspecified = 0, Udp = 1, Tcp = 2 }`. I can do `message.proto = Direction::Out as i32` and it will work. I can do `Direction::from_i32(message.proto)` and it'll work. And I like Rust's strict type system keeping an eye on me.

So I was wondering if there could be more convenient and safer alternative. What about:

* Create the enum as it is now, eg `enum Direction { Unspecified = 0, In = 1, Out = 2 }`
* Also create a companion `struct DirectionRaw(pub i32)`

This way, we can have conversion methods on both of them to each other, but not with i32 directly (type safety). The fact the conversion methods would be on the `DirectionRaw` would make it more discoverable.

Furthermore, I think the conversion method would be something like `fn enum(&self) -> Option<Direction>` ‒ this way it is possible to both know if the input was valid/known and call `unwrap_or_default()` on it to get the appropriate default.

Does that make sense? Or does it have some downsides I don't see?

I would be willing to implement it, but I wanted to check first if it makes sense.

**Comment by danburkert** [comment]
@vorner have you seen the getters/setters that are generated for enumeration fields?  Checkout this comment for more info: https://github.com/danburkert/prost/issues/69#issuecomment-357777266

**Comment by vorner** [comment]
I did have a look and these are some help for the first point, but it is still methods on the whole message, not on the field, which feels a bit unexpected (considering the other fields are just fields). But it doesn't address the second point, eg weak typing.

**Comment by danburkert** [comment]
I'm not really sure what you mean by weak typing?  Both the fields and getter/setter are strongly typed.  I definitely think the current system is simpler than adding a whole new type.  As far as whether it's expected/unexpected for it to be a method instead of field accessor, I'm not really concerned.  There are other places where prost is already adding helper methods per field, e.g. proto2 optional fields.

**Comment by vorner** [comment]
I mean the fact that all enumerations are integers and can be assigned to each other even if they are of different enum type, similar to how everything is int in C and one has to be careful not to mix things up.

It isn't a show-stopper, I'm just thinking of possible improvements. Not that I'd already have a bug in that sense, but then, I have some history of C development and I don't mix „conceptual“ types on regular basis thanks to that.

**Comment by danburkert** [comment]
@Nemo157 while technically possible, that would mean that `prost` can't be used for applications that require schema evolution.  I'm not going to implement it, because I think schema evolution is critical to all applications, eventually.  Properly handling this is one of the reasons I wrote `prost`; the other existing implementation at the time doesn't work with unknown enum values, and its (stable) typed API means that it _can't_.

I'm unconvinced that the type-safety thing is an issue in practice (I've certainly never been bitten by it, since the getter/setter tend to be more ergonomic anyway), but if its a real concern then I think the best solution would be an option to make enum fields private instead of public, which would enforce that access go through the typed getters/setters.

**Comment by danburkert** [comment]
I should note, `prost` clearly needs a generated code guide, a la [Go's](https://developers.google.com/protocol-buffers/docs/reference/go-generated).  I think that would clear up a lot of this confusion.  That should probably be its own issue though.

**Comment by Nemo157** [comment]
I don't see how this would limit applications that require schema evolution any more than the currently generated code does. If the generated code is publicly exported then you are already exposing an enum that might have more variants added to it in the future, if you're not publicly exporting it then when you update your schema you can update the code simultaneously.

My problem is that every time I deal with a message I need to create my own error if the message contains an enum value I don't currently support:

```protobuf
package data;

enum KeyType {
  RSA = 0;
}

message PublicKey {
  required KeyType Type = 1;
  required bytes Data = 2;
}
```

```rust
pub fn from_protobuf(bytes: &[u8]) -> Result<Self> {
    let message = data::PublicKey::decode(bytes)?;
    let type_ = data::KeyType::from_i32(message.type_)
        .ok_or_else(|| format!("Unknown KeyType {}", message.type_))?;
    match type_ {
        data::KeyType::Rsa => {
            Ok(Self::from_bytes_rsa(message.data))
        }
    }
}
```

I'm never going to do anything else, my code has no idea what semantics new enum values will have associated with them so there's no way for me to attempt to handle them.

> I think the best solution would be an option to make enum fields private instead of public, which would enforce that access go through the typed getters/setters.

This would be much worse than the current situation. I took a look at the generated method and was very surprised it wasn't just `ENUM_TYPE::from_i32` but instead returns a default value if it doesn't understand the provided value. That's definitely going to break any application that receives a value it doesn't understand. For example the schema above could be extended in the future with something like `KeyType::ECDH = 1`, if that happens and a client using the updated schema sends a message with `type_ = 1` to a client using the `message.type_()` method it will not know what `1` means and just default to using `KeyType::Rsa`, almost certainly breaking downstream code.

**Comment by Nemo157** [comment]
For reference I've got a partially implemented branch acting how I mentioned: https://github.com/Nemo157/prost/tree/enumeration-as-enum

This is controlled via an extra config value for `prost_build::Config` that says to use the enum types for the fields, which is passed through to `prost_derive` to adjust the code generation.

**Comment by Nemo157** [comment]
> Schema evolution has nothing to do with Rust source API compatibility, it's about protocol compatibility and flexibility. [...]

Ok, so just to clarify for me, when you're mentioning schema evolution you're talking about having `prost`'s design guide application developers towards supporting schema evolution, rather than any inherent support for schema evolution in `prost` itself?

> Well-designed applications can often recover from receiving unknown enum variants.

I don't disagree with this. Which is why I suggest this as a configurable feature of the code generator, not a default.

I guess a large part of my issue is that I'm having to deal with third-party protocols that are not using protobuf best practices. As far as I can tell there is no real support for schema evolution built into these protocols, there's no way to send back a generic error message let alone a "you used a newer feature I don't understand" message. Instead the protocols are version negotiated at a higher level and presumably would have a new version if the schema changes.

If you want to limit `prost`s APIs to be ergonomic only when using protobuf best practices, then I guess that's your call and I'll just have to write macros to make this easier for me to deal with.

**Comment by brain0** [comment]
Sorry to hijack this issue, but I have been looking at prost, and I also think enums should be handled better - and Rust enums give the perfect tool for this. prost would have to add a type like this:

```rust
enum EnumField<T> {
    KnownVariant(T),
    UnknownVariant(i32),
}
```

The following proto3 example:
```protobuf
enum City {
  Unknown = 0;
  NewYork = 1;
  London = 2;
  Paris = 3;
}
message Foo {
  City city = 1;
}
```
would generate something like this:
```rust
enum City {
    Unknown = 0,
    NewYork = 1,
    London = 2,
    Paris = 3,
}
struct Foo {
    city: EnumField<City>,
}
```

This is idiomatic Rust and handles both cases cleanly. I know this would be a breaking change, but since prost does not have a 1.0 version yet, it would be the right time to add this.

**Comment by danburkert** [comment]
@brain0 are you aware that Rust enums are generated, and you can get the enum value from a field already with the generated accessor method?  See this comment for more info: https://github.com/danburkert/prost/issues/69#issuecomment-357777266.

**Comment by brain0** [comment]
I am aware of that, and from what I can see in the comment, you can either get the i32, or you can get the enum, but in the latter case, you simply fall back to the default if it is out of range. I don't see a way to easily determine that the value was out of range, other than comparing the i32 value against known values manually. The version I just proposed is more obvious and allows to explicitly distinguish between the case of a valid enum value and an unknown one, without losing any information.

Accessing the enum field via `match` or `if let` expressions to determine whether the enum value was in range feels natural in Rust code. At least to me, having two ways to access the same value, both giving me incomplete information in the worst case, does not feel natural at all. In other places, prost generated code has an elegance that other protobuf implementations lack (have you seen protobuf generated C++ code?), but the enums feel wrong.

**Comment by danburkert** [comment]
@Nemo157 

> An alternative that I think may fit the intent of protobufs enums better is just a new-typed integer, one of the most widely used example of this are http's StatusCode.

That's an interesting suggestion, I hadn't considered associated consts.  That being said I don't find the `match foo.city` example convincing.  In what cases wouldn't you treat the `City::UNKNOWN` case exactly like the `other` case?

@brain0 

> I don't see a way to easily determine that the value was out of range, other than comparing the i32 value against known values manually.

See the [previous comment](https://github.com/danburkert/prost/issues/69#issuecomment-357775539), all enum types get `is_valid` and `from_i32` methods which do exactly what you want.  `from_i32` returns `Option::None` if the `i32` isn't valid, but it could be changed to `Result<EnumType, i32>` if that's deemed to be more useful.

> Accessing the enum field via match or if let expressions to determine whether the enum value was in range feels natural in Rust code. At least to me, having two ways to access the same value, both giving me incomplete information in the worst case, does not feel natural at all.

Again I'm repeating myself, but the recommended way to use enums in Protobuf is to *always* have the first variant be `Unknown`.  If you do that, then all you need to worry about is handling the `Unknown` case in the vast majority of situations.  I _have_ used the C++ and Java protobuf libraries extensively for building many systems, and in my experience it's extremely rare to need to handle a distinction between `Unknown` and unrecognized values.

**Comment by Nemo157** [comment]
@danburkert There is one reason, more contextual information if you're trying to debug an issue. The `Unknown` variant loses the actual value sent, if you want to get that currently you have to use something like `City::from_i32(foo.city).ok_or_else(|| Error::new(format!("Unknown City {}", message.type_)))?` instead of the provided `foo.city()` method.

The other reason I want it is to integrate with third-party protocols that don't use unknown variants and instead communicate versions out of band. As an example in `prost` itself the [`FieldDescriptorProto::Type` enum](https://github.com/danburkert/prost/blob/master/prost-build/third-party/protobuf/include/google/protobuf/descriptor.proto#L137-L168) doesn't have an unknown variant, so if there were a new field type added `prost` would treat that as a `double` instead of erroring out.

**Comment by danburkert** [comment]
@Nemo157 

> There is one reason, more contextual information if you're trying to debug an issue....

Sure, good example.  I'd solve it like this:

```rust
match foo.city {
    City::UNKNOWN => { return Err(Error::from(format!("Unknown city {}", foo.city))); }
    City::NEW_YORK => { ... }
    City::LONDON => { ... }
    City::PARIS => { ... }
}
```

> The other reason I want it is to integrate with third-party protocols that don't use unknown variants and instead communicate versions out of band. As an example in prost itself the FieldDescriptorProto::Type enum doesn't have an unknown variant, so if there were a new field type added prost would treat that as a double instead of erroring out.

Yep, I've definitely run into this myself.  As a concrete example, [CodeGenerator::resolve_type](https://github.com/danburkert/prost/blob/master/prost-build/src/code_generator.rs#L601) doesn't currently check whether the field type is known[1].  Using the current `prost` APIs I'd add an assert like this at the top of the function to solve this:

```rust
assert!(field.type_.map(Type::is_valid).unwrap_or(false),
        format!("field {} has an unknown type: {:?}", field.name(), field.type_));
```

Would one of the suggestions simplify that pattern?

[1]: I was aware of this when I wrote it, but chose to ignore the issue because the Protobuf spec hasn't added a new field type in as long as I'm aware of, and if it did it would only cause a problem if you happened to run an old `prost` version with a new `protoc`, which would be rare.

**Comment by vorner** [comment]
The associated constants thing look interesting ‒ they better describe the reality than the enum I think.

But I'd still like to have the real enum, even if I don't have to use it ‒ oftentimes, I want to extract the data from the message, validate it and then keep using the data through the application. And knowing it is one of the variants I know (and having rustc check I handle all of them) is convenient.

**Comment by brain0** [comment]
> Again I'm repeating myself, but the recommended way to use enums in Protobuf is to always have the first variant be Unknown

proto3 says that there must be a variant with value 0 that is the default. It doesn't necessarily correspond to "Unknown". For instance, imagine that you sell products and have several third parties that handle delivery for you. Then imagine the following enum:
```proto3
enum DeliveryTime {
    DontCare = 0;
    Morning = 1;
    Noon = 2;
    Afternoon = 3;
}
```
Then, at some point you add night time delivery. Now there is an important difference between "default value" (don't care) and "unknown value" (some preference which we don't know and need to clarify).

> If you want to limit prosts APIs to be ergonomic only when using protobuf best practices, then I guess that's your call and I'll just have to write macros to make this easier for me to deal with.

I would want APIs that are obvious and ergonomic for all cases. IMO, the current implementation is not very ergonomic for either case - and as this bug report show, not obvious either.

I'd like to extend on my previous suggestion (EnumField enum) to show how one could create APIs that look very much like typical Rust std APIs and IMO are very ergonomic in all use cases (use case example at the bottom of the code snippet):

```rust
// code in prost
#[derive(Copy, Clone, Debug)]
enum EnumField<T> {
    KnownVariant(T),
    UnknownVariant(i32),
}

impl<T> EnumField<T> {
    fn unwrap(self) -> T {
        match self {
            EnumField::KnownVariant(v) => v,
            EnumField::UnknownVariant(_) => panic!("Some panic message"),
        }
    }
}

impl<T: Default> EnumField<T> {
    fn unwrap_or_default(self) -> T {
        match self {
            EnumField::KnownVariant(v) => v,
            EnumField::UnknownVariant(_) => T::default(),
        }
    }
}

impl<T: Default> Default for EnumField<T> {
    fn default() -> Self {
        EnumField::KnownVariant(T::default())
    }
}

impl<T> From<T> for EnumField<T> {
    fn from(t: T) -> Self {
        EnumField::KnownVariant(t)
    }
}

impl<T> From<EnumField<T>> for i32
where
    i32: From<T>,
{
    fn from(v: EnumField<T>) -> i32 {
        match v {
            EnumField::KnownVariant(v) => v.into(),
            EnumField::UnknownVariant(v) => v,
        }
    }
}

// to be replaced with TryFrom<i32> once that is stable
trait TryFromI32: Sized {
    fn try_from_i32(v: i32) -> Option<Self>;
}

impl<T: TryFromI32> From<i32> for EnumField<T> {
    fn from(v: i32) -> EnumField<T> {
        match T::try_from_i32(v) {
            Some(v) => EnumField::KnownVariant(v),
            None => EnumField::UnknownVariant(v),
        }
    }
}

// generated enum example
#[derive(Copy, Clone, Debug)]
enum DeliveryTime {
    DontCare = 0,
    Morning = 1,
    Noon = 2,
    Afternoon = 3,
}

impl From<DeliveryTime> for i32 {
    fn from(v: DeliveryTime) -> Self {
        v as i32
    }
}

impl Default for DeliveryTime {
    fn default() -> Self {
        DeliveryTime::DontCare
    }
}

impl TryFromI32 for DeliveryTime {
    fn try_from_i32(v: i32) -> Option<Self> {
        match v {
            0 => Some(DeliveryTime::DontCare),
            1 => Some(DeliveryTime::Morning),
            2 => Some(DeliveryTime::Noon),
            3 => Some(DeliveryTime::Afternoon),
            _ => None,
        }
    }
}

// code example
fn main() {
    let val = DeliveryTime::Morning;

    // assign message field from enum value
    let v: EnumField<DeliveryTime> = val.into();

    // assign default value to field
    let _: EnumField<DeliveryTime> = Default::default();

    // Use enum, panic if out of range
    let _ = v.unwrap();

    // Use enum, use default if out of range (your current accessor method)
    let _ = v.unwrap_or_default();

    // Get underlying i32
    let _: i32 = v.into();

    // Convert i32 to enum
    let _: EnumField<DeliveryTime> = 17i32.into();
}
```

**Comment by danburkert** [comment]
> Then, at some point you add night time delivery. Now there is an important difference between "default value" (don't care) and "unknown value" (some preference which we don't know and need to clarify).

That's exactly why the best practice is to *always have the first variant be Unknown*.  Not sure how to say this more clearly, but something must be getting lost in translation as this is at least the second time in this thread that I'm repeating myself.  Keep in mind that this is a best practice no matter what language bindings you are using.  Creating a special API for `prost` so that you don't have to follow this best practice means you won't be following the best practice for C++, Java and all other languages.  To quote myself again,

> ... this behavior is common to all official protocol buffer implementations, and it makes working with protocol buffers easier in the majority of cases, as long as you understand the rules and best practices. prost's goal is emphatically not to shield users from from having to understand protobuf best practices (although where possible it does make best practices straightforward).

> I'd like to extend on my previous suggestion (EnumField enum) to show how one could create APIs that look very much like typical Rust std APIs and IMO are very ergonomic in all use cases (use case example at the bottom of the code snippet):

This example doesn't actually use the enum type as a field in a message, so it's impossible to compare the ergonomics of this alternate API.
